services:
  surveillance-node:
    container_name: surveillance-node
    build:
      context: .
      dockerfile: Dockerfile
    image: surveillance-node:latest
    restart: unless-stopped
    network_mode: host
    privileged: true
    env_file:
      - .env
    environment:
      SSL_CERT_PATH: /app/cert.pem
      SSL_KEY_PATH: /app/key.pem
    volumes:
      - ./cert.pem:/app/cert.pem:ro
      - ./key.pem:/app/key.pem:ro
      - /dev:/dev
      - /dev/snd:/dev/snd
      - /run/udev:/run/udev:ro
    group_add:
      - audio
      - video
